import { invoke } from '@tauri-apps/api/core'
import type { Account, AccountInput, AppLog, BackupData, ChatContact, ChatContactsPage, ChatEmoji, ChatMessage, ChatMessagesPage, CustomerProfile, DashboardStats, Order, OrderInput, Product, ProductInput, QrLoginStart, QrLoginStatus, QuickReply, QuickReplyImage, SyncJob, SyncResult } from './types'

export const api = {
  dashboard: () => invoke<DashboardStats>('dashboard_stats'),
  accounts: () => invoke<Account[]>('list_accounts'),
  products: (accountId?: string) => invoke<Product[]>('list_products', { accountId }),
  orders: (accountId?: string) => invoke<Order[]>('list_orders', { accountId }),
  relatedOrders: (accountId: string, chatId: string, status = '全部') => invoke<Order[]>('list_related_orders', { accountId, chatId, status }),
  createAccount: (input: AccountInput) => invoke<Account>('create_account', { input }),
  updateAccount: (id: string, input: AccountInput) => invoke<Account>('update_account', { id, input }),
  updateConversationName: (accountId: string, conversationName: string) => invoke<Account>('update_conversation_name', { accountId, conversationName }),
  deleteAccount: (id: string) => invoke<void>('delete_account', { id }),
  syncAccount: (accountId: string) => invoke<SyncResult>('sync_account', { accountId }),
  syncJobs: (accountId?: string) => invoke<SyncJob[]>('list_sync_jobs', { accountId }),
  generateQrLogin: () => invoke<QrLoginStart>('generate_qr_login'),
  checkQrLoginStatus: (sessionId: string) => invoke<QrLoginStatus>('check_qr_login_status', { sessionId }),
  chatContacts: (accountId: string) => invoke<ChatContact[]>('list_chat_contacts', { accountId }),
  customerProfile: (accountId: string, chatId: string) => invoke<CustomerProfile>('customer_profile', { accountId, chatId }),
  updateCustomerRemark: (accountId: string, chatId: string, remark: string) => invoke<string>('update_customer_remark', { accountId, chatId, remark }),
  chatUnreadTotals: () => invoke<Record<string, number>>('chat_unread_totals'),
  imStatuses: () => invoke<Record<string, string>>('get_im_statuses'),
  appLogs: (limit = 300) => invoke<AppLog[]>('list_app_logs', { limit }),
  startChatListener: (accountId: string) => invoke<void>('start_chat_listener', { accountId }),
  stopChatListener: (accountId: string) => invoke<void>('stop_chat_listener', { accountId }),
  syncChatContacts: (accountId: string, cursor: number | null = null) => invoke<ChatContactsPage>('sync_chat_contacts', { accountId, cursor }),
  markChatRead: (accountId: string, chatId: string) => invoke<void>('mark_chat_read', { accountId, chatId }),
  setChatPinned: (accountId: string, chatId: string, pinned: boolean) => invoke<void>('set_chat_pinned', { accountId, chatId, pinned }),
  deleteChatConversation: (accountId: string, chatId: string) => invoke<void>('delete_chat_conversation', { accountId, chatId }),
  chatMessages: (accountId: string, chatId: string) => invoke<ChatMessage[]>('list_chat_messages', { accountId, chatId }),
  chatEmojis: (accountId: string) => invoke<ChatEmoji[]>('list_chat_emojis', { accountId }),
  syncChatEmojis: (accountId: string) => invoke<ChatEmoji[]>('sync_chat_emojis', { accountId }),
  syncChatMessages: (accountId: string, chatId: string, cursor: number | null = null) => invoke<ChatMessagesPage>('sync_chat_messages', { accountId, chatId, cursor }),
  openProductDetail: (accountId: string, url: string) => invoke<void>('open_product_detail', { accountId, url }),
  shipOrderWithoutParcel: (accountId: string, orderNo: string, tradeText: string) => invoke<void>('ship_order_without_parcel', { accountId, orderNo, tradeText }),
  shipOrderWithLogistics: (accountId: string, orderNo: string, mailNo: string) => invoke<void>('ship_order_with_logistics', { accountId, orderNo, mailNo }),
  cancelOrderBySeller: (accountId: string, orderNo: string, reason: string) => invoke<void>('cancel_order_by_seller', { accountId, orderNo, reason }),
  sendChatMessage: (accountId: string, chatId: string, receiverUserId: string, text: string) => invoke<ChatMessage>('send_chat_message', { accountId, chatId, receiverUserId, text }),
  sendChatImage: (accountId: string, chatId: string, receiverUserId: string, fileName: string, mimeType: string, imageData: string, width: number, height: number) => invoke<ChatMessage>('send_chat_image', { accountId, chatId, receiverUserId, fileName, mimeType, imageData, width, height }),
  sendChatProduct: (accountId: string, chatId: string, receiverUserId: string, itemId: string, title: string, imageUrl: string, price: number) => invoke<ChatMessage>('send_chat_product', { accountId, chatId, receiverUserId, itemId, title, imageUrl, price }),
  quickReplies: (accountId: string) => invoke<QuickReply[]>('list_quick_replies', { accountId }),
  createQuickReply: (accountId: string, title: string, content: string, shortCode: string, images: QuickReplyImage[]) => invoke<QuickReply>('create_quick_reply', { accountId, title, content, shortCode, images }),
  updateQuickReply: (id: string, accountId: string, title: string, content: string, shortCode: string, images: QuickReplyImage[]) => invoke<QuickReply>('update_quick_reply', { id, accountId, title, content, shortCode, images }),
  deleteQuickReply: (id: string) => invoke<void>('delete_quick_reply', { id }),
  createProduct: (input: ProductInput) => invoke<Product>('create_product', { input }),
  updateProduct: (id: string, input: ProductInput) => invoke<Product>('update_product', { id, input }),
  deleteProduct: (id: string) => invoke<void>('delete_product', { id }),
  updateProductsStatus: (ids: string[], status: string) => invoke<number>('update_products_status', { ids, status }),
  deleteProducts: (ids: string[]) => invoke<number>('delete_products', { ids }),
  createOrder: (input: OrderInput) => invoke<Order>('create_order', { input }),
  updateOrder: (id: string, status: string, note: string) => invoke<Order>('update_order', { id, status, note }),
  deleteOrder: (id: string) => invoke<void>('delete_order', { id }),
  updateOrdersStatus: (ids: string[], status: string) => invoke<number>('update_orders_status', { ids, status }),
  exportBackup: () => invoke<BackupData>('export_backup'),
}
